### ISSUE TITLE
Issues with running an topology.jar

### ISSUE THREAD

**Issue by abhaymehtre** [31z4/storm-docker#26]
I have pulled out the image for the storm and as per the listed steps , I have got the nimbus and storm UI working. But unfortuantely the while running the jar, the situation below is arised.

 /usr/local/openjdk-8/bin/java -client -Ddaemon.name= -Dstorm.options= -Dstorm.home=/apache-storm-2.1.0 -Dstorm.log.dir=/logs -Djava.library.path=/usr/local/lib:/opt/local/lib:/usr/lib:/usr/lib64 -Dstorm.conf.file= -cp /apache-storm-2.1.0/*:/apache-storm-2.1.0/lib/*:/apache-storm-2.1.0/extlib/*:/topology.jar:/conf:/apache-storm-2.1.0/bin: -Dstorm.jar=/topology.jar -Dstorm.dependency.jars= -Dstorm.dependency.artifacts={} org.apache.storm.starter.ExclamationTopology

I am not even able to get access to the localhost:6627 even after deploying.

**Comment by 31z4** [comment]
What you described as "the situation below" looks jut like command line arguments rather than an actual error.

Please either follow https://github.com/31z4/storm-docker/blob/master/.github/issue_template.md or provide as much information as possible in free-form (including commands you ran and their output).

**Comment by 31z4** [comment]
Closing it because the issue seems to be inactive for quite some time now.
