### ISSUE TITLE
Create a `logviewer` image variant

### ISSUE THREAD

**Issue by 31z4** [31z4/storm-docker#3]
It will allow to see the logs from the Storm UI. Both `logviewer` and `storm` processes must be run  under [`Supervisor`](http://supervisord.org/).

**Comment by edbo** [comment]
I'm actually trying to see if I can get this working in a more 'docker' friendly way.

I'd prefer if we can get the logs out through stdout so it could be sent through something like logspout or fluentd which fits in with what I would expect most people to be doing in a docker cluster.

Just a thought for now but I'll post back here if I make any progress.

**Comment by edbo** [comment]
This actually turned out to be easier than I expected:

https://github.com/edbo/storm-docker/commit/3d11d18993e4f748ea717eed8c3308dd6dc641a7

The downside of this is you lose the separate files for stats etc... but the upside is it doesn't assume anything about the cluster it runs on and how said cluster wants to consume logs and metrics.

**Comment by 31z4** [comment]
@edbo I agree that it may make sense in the cluster environment. But on the other hand it's convenient to have logs available in the UI as well as to be able to perform distributed log search.
